# runtime: nodejs
# env: flex

runtime: nodejs20
instance_class: F1
service: default

automatic_scaling:
#   target_cpu_utilization: 0.65
  # min_instances: 1
  # min_instances: 1
#   max_instances: 100
#   max_pending_latency: automatic
#   max_concurrent_requests: 50

handlers:
  - url: /_nuxt
    static_dir: .output/public/_nuxt
    secure: always

  - url: /(.*\.(gif|png|jpg|ico|txt))$
    static_files:  .output/public/.*\.(gif|png|jpg|ico|txt)$
    upload: public/.*\.(gif|png|jpg|ico|txt)$
    secure: always

  - url: /.*
    script: auto
    secure: always
    
env_variables:
  NUXT_HOST: "0.0.0.0"
  NUXT_PORT: "8080"
  NODE_ENV: "production"

# inbound_services:
#   - warmup
